name: Ping GitHub Codespace per 15 minutes

on:
  schedule:
    # 每 15 分钟触发一次，保持 Codespace 活跃
    - cron: '*/15 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Ping GitHub Codespace per 15 minutes
      run: |
        curl -IL https://literate-enigma-gvvv4v4j44v3p57.github.dev
